### ISSUE TITLE
Error HTTP/1.1 403 Forbidden ..

### ISSUE THREAD

**Issue by protocol0pw** [vogtpatrick/Ethereum-Wallet-Cracker#1]
Hi, I got an error. I am pressing "Start" and after 1-2 seconds I am getting this error and I don't know what to do. I am also interested if it's possible to update your software to save text documents as logs with every Private Key/Public address/ETH Balance. Thanks a lot!

<img width="578" alt="screenshot 2018-11-06 at 15 09 12" src="https://user-images.githubusercontent.com/44806937/48066407-2b451a00-e1d6-11e8-8771-5af31e542043.png">

**Comment by su314ka** [comment]
From what I saw the error message is appearing if you run the software simultaneously on 2 PC`s in the same network.

**Comment by sssergy** [comment]
https://www.virustotal.com/ru/file/44e257afb12a32c59d9e39b913bcfea0189a10a3144e854bb994d52ece03e0ec/analysis/1541685985/
